"""empty message

Revision ID: 047288a9cd1f
Revises: a0572acb6028
Create Date: 2016-12-13 19:39:40.702473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047288a9cd1f'
down_revision = 'a0572acb6028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    op.drop_table('Associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Associations',
    sa.Column('node_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permissions', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'user_id')
    )
    op.drop_table('Association')
    # ### end Alembic commands ###
