"""empty message

Revision ID: 1a8088b9d1bb
Revises: 8a464d5585b9
Create Date: 2016-12-13 16:54:29.560554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8088b9d1bb'
down_revision = '8a464d5585b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.Integer(), nullable=True),
    sa.Column('dat_start', sa.String(length=64), nullable=True),
    sa.Column('dat_end', sa.String(length=64), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Node_ip_address'), 'Node', ['ip_address'], unique=True)
    op.create_index(op.f('ix_Node_name'), 'Node', ['name'], unique=False)
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_index(op.f('ix_Node_name'), table_name='Node')
    op.drop_index(op.f('ix_Node_ip_address'), table_name='Node')
    op.drop_table('Node')
    # ### end Alembic commands ###
