"""empty message

Revision ID: a0572acb6028
Revises: 1a8088b9d1bb
Create Date: 2016-12-13 17:26:47.244771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0572acb6028'
down_revision = '1a8088b9d1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Associations',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'user_id')
    )
    op.drop_table('nodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('permissions', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.drop_table('Associations')
    # ### end Alembic commands ###
