"""empty message

Revision ID: b41305d0ee6f
Revises: 2b8823c4da6d
Create Date: 2016-12-12 04:03:58.732467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41305d0ee6f'
down_revision = '2b8823c4da6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'confirmed')
    # ### end Alembic commands ###
